version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer-service
    command: node dist/apps/producer-app/main.js
    ports:
      - '3001:3000' 
    env_file:
      - .env

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-service
    command: node dist/apps/consumer-app/main.js
    ports:
      - '3002:3000'
    env_file:
      - .env
